spring:
  application:
    name: dairy-backend
  data:
    mongodb:
      uri: mongodb+srv://gajananmagar004_db_user:OJgp4EnQLg7tsvYa@cluster0.eobdyd7.mongodb.net/dairy_db?appName=Cluster0

server:
  port: ${PORT:8080}
