package com.dairy.backend.scheduler;

import com.dairy.backend.service.MilkEntryService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDate;

@Component
@RequiredArgsConstructor
@Slf4j
public class ScheduledTasks {

    private final MilkEntryService milkEntryService;

    // Run every day at 9:00 PM (21:00)
    @Scheduled(cron = "0 0 21 * * ?")
    public void autoGenerateDailyMilkEntries() {
        log.info("Running scheduled task: Auto-generating daily milk entries for date: {}", LocalDate.now());
        try {
            int count = milkEntryService.autoGenerateEntries(LocalDate.now());
            log.info("Scheduled task completed. Successfully auto-generated {} milk entries.", count);
        } catch (Exception e) {
            log.error("Error occurred while auto-generating daily milk entries", e);
        }
    }
}
