package com.dairy.backend.scheduler;

import com.dairy.backend.entity.User;
import com.dairy.backend.repository.UserRepository;
import com.dairy.backend.service.MilkEntryService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashSet;
import java.util.Set;

@Component
@RequiredArgsConstructor
@Slf4j
public class ScheduledTasks {

    private static final String DEFAULT_AUTO_ENTRY_TIME = "21:30";
    private static final ZoneId AUTO_ENTRY_ZONE = ZoneId.of("Asia/Kolkata");
    private static final DateTimeFormatter TIME_FORMATTER = DateTimeFormatter.ofPattern("HH:mm");

    private final MilkEntryService milkEntryService;
    private final UserRepository userRepository;

    // Run every minute and trigger auto entry for users whose configured time matches now.
    @Scheduled(cron = "0 * * * * ?", zone = "Asia/Kolkata")
    public void autoGenerateDailyMilkEntries() {
        LocalDate currentDate = LocalDate.now(AUTO_ENTRY_ZONE);
        String currentTime = LocalTime.now(AUTO_ENTRY_ZONE).format(TIME_FORMATTER);
        log.info("Running scheduled task: Checking auto-entry schedules for date {} at {}", currentDate, currentTime);
        try {
            int count = 0;
            for (User user : userRepository.findAll()) {
                String autoEntryTime = resolveAutoEntryTime(user);
                if (!currentTime.equals(autoEntryTime)) {
                    continue;
                }
                for (String userId : resolveOwnedUserIds(user)) {
                    count += milkEntryService.autoGenerateEntriesForUser(userId, currentDate);
                }
            }
            log.info("Scheduled task completed. Successfully auto-generated {} milk entries.", count);
        } catch (Exception e) {
            log.error("Error occurred while auto-generating daily milk entries", e);
        }
    }

    private String resolveAutoEntryTime(User user) {
        if (user.getAutoEntryTime() == null || user.getAutoEntryTime().isBlank()) {
            return DEFAULT_AUTO_ENTRY_TIME;
        }
        return user.getAutoEntryTime();
    }

    private Set<String> resolveOwnedUserIds(User user) {
        Set<String> userIds = new LinkedHashSet<>();
        if (user.getId() != null && !user.getId().isBlank()) {
            userIds.add(user.getId());
        }
        if (user.getPhone() != null && !user.getPhone().isBlank()) {
            userIds.add(user.getPhone());
        }
        if (user.getEmail() != null && !user.getEmail().isBlank()) {
            userIds.add(user.getEmail());
        }
        return userIds;
    }
}
